name: Bug report
description: Report a broken behavior in one of the apps
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Please do not include secrets (API keys, tokens, passwords) or personal data.
  - type: input
    id: app
    attributes:
      label: App
      description: Which folder/app is affected?
      placeholder: "chowsr"
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: What did you expect vs what actually happened?
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. …
        2. …
        3. …
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs / screenshots
      description: Paste relevant output (redact secrets).
      render: shell

